# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Feracore Support
description: Feracore için yardıma mı ihtiyacınız var? Biz seninleyiz. Başlangıçtan özelleştirmeye kadar, Feracore ile ilgili her şey için yardım bulun.
baseurl:  # the subpath of your site, e.g. /support
url: https://destek.feracore.com # the base hostname AND PROTOCOL for your site, e.g. http://example.com
permalink: /:categories/:title
future: true

content_type: Bilgi Tabanı ve Yardım Merkezi #Define whether this is a knowledge base, help center, or something else
use_authors: false #Set this to false to disable showing post authors

brand_logo: logo.png
brand_name: Feracore
header: Nasıl yardımcı olabiliriz?
subheader: Feracore için destek ve dokümanlar

meta_image: feracore-meta.png

# Social Links
twitter_username: Feracore
facebook_page:
github_username: 
email: feracore@ekofi.science
linkedin_page: https://www.linkedin.com/in/fsuaterdogan/
instagram_username: fsuaterdogan


# Navivation
nav_item_one: English
nav_item_one_link: https://docs.feracore.com

nav_item_two: Twitter
nav_item_two_link: https://twitter.com/Feracore

nav_item_three: #
nav_item_three_link: #

nav_button: Feracore'a Geri Dön
nav_button_link: https://www.feracore.com

# More Help
help_one_title: Geri Bildirim ve Teknik Hatalar
help_one_content: Bu projeyle ilgili herhangi bir geri bildirim vermek isterseniz ya da hata - sorun bulursanız, lütfen e-posta göndermekten çekinmeyin.
help_one_button: E-Posta
help_one_link: mailto:proxima@ekofi.science

help_two_title: Twitter
help_two_content: Feracore için önerileriniz varsa bize tweet atabilirsiniz. Ya da sadece merhaba demek isterseniz.
help_two_button: Twitter
help_two_link: https://twitter.com/Feracore

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-last-modified-at

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#


sass:
  sass_dir:          _scss
  style:            :compressed
